name: GitHub Actions Vercel Production Deployment
on:
  push:
    branches:
      - develop
jobs:
  Build-Projects:
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build Admin Project
        run: yarn nx build sillok-admin --prod
      - name: Build User Project
        run: yarn nx build sillok-user --prod
      - name: Copy Admin Build Output
        run: |
          mkdir -p apps/sillok-admin/dist
          cp -r dist/apps/sillok-admin/* apps/sillok-admin/dist/ || echo "No admin build output found"
      - name: Copy User Build Output
        run: |
          mkdir -p apps/sillok-user/dist
          cp -r dist/apps/sillok-user/* apps/sillok-user/dist/ || echo "No user build output found"
      - name: Upload Admin Build
        uses: actions/upload-artifact@v3
        with:
          name: admin-build
          path: apps/sillok-admin
      - name: Upload User Build
        uses: actions/upload-artifact@v3
        with:
          name: user-build
          path: apps/sillok-user

  Deploy-Admin:
    needs: Build-Projects
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - name: Download Admin Build
        uses: actions/download-artifact@v3
        with:
          name: admin-build
          path: admin
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_ADMIN_PROJECT_ID }}
          working-directory: admin
          vercel-args: '--prod'

  Deploy-User:
    needs: Build-Projects
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - name: Download User Build
        uses: actions/download-artifact@v3
        with:
          name: user-build
          path: user
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_USER_PROJECT_ID }}
          working-directory: user
          vercel-args: '--prod'
