name: GitHub Actions Vercel Production Deployment
on:
  push:
    branches:
      - develop
jobs:
  Deploy-Projects:
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build Admin Project
        run: yarn nx build sillok-admin --prod
      - name: Build User Project
        run: yarn nx build sillok-user --prod
      - name: Copy Admin Build Output
        run: |
          mkdir -p apps/sillok-admin/dist
          cp -r dist/apps/sillok-admin/* apps/sillok-admin/dist/ || echo "No admin build output found"
      - name: Copy User Build Output
        run: |
          mkdir -p apps/sillok-user/dist
          cp -r dist/apps/sillok-user/* apps/sillok-user/dist/ || echo "No user build output found"
          
      - name: Install Vercel CLI
        run: npm install -g vercel
        
      - name: Deploy Admin to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_ADMIN_PROJECT_ID }}
        run: |
          cd apps/sillok-admin
          vercel deploy --prod --token=$VERCEL_TOKEN
          
      - name: Deploy User to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_USER_PROJECT_ID }}
        run: |
          cd apps/sillok-user
          vercel deploy --prod --token=$VERCEL_TOKEN
