name: GitHub Actions Vercel Production Deployment
on:
  push:
    branches:
      - develop
jobs:
  Deploy-Admin-Production:
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build Admin Project
        run: yarn nx build sillok-admin
      - name: Create Deploy Directory
        run: |
          mkdir -p static-admin
          cp -rv apps/sillok-admin/dist/* static-admin/
          echo '{"version":2,"public":true,"cleanUrls":true,"rewrites":[{"source":"/(.*)", "destination":"/index.html"}]}' > static-admin/vercel.json
          echo '{"name":"sillok-admin","devCommand":"npx serve .","outputDirectory":"."}' > static-admin/package.json
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_ADMIN_PROJECT_ID }}
          working-directory: ./static-admin
          vercel-args: '--prod --confirm'

  Deploy-User-Production:
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build User Project
        run: yarn nx build sillok-user
      - name: Create Deploy Directory
        run: |
          mkdir -p static-user
          cp -rv apps/sillok-user/dist/* static-user/
          echo '{"version":2,"public":true,"cleanUrls":true,"rewrites":[{"source":"/(.*)", "destination":"/index.html"}]}' > static-user/vercel.json
          echo '{"name":"sillok-user","devCommand":"npx serve .","outputDirectory":"."}' > static-user/package.json
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_USER_PROJECT_ID }}
          working-directory: ./static-user
          vercel-args: '--prod --confirm'
